package app

import (
	"os"
	"strings"
	"testing"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

func keyMsg(value string) tea.KeyMsg {
	switch value {
	case "down":
		return tea.KeyMsg{Type: tea.KeyDown}
	case "up":
		return tea.KeyMsg{Type: tea.KeyUp}
	case "enter":
		return tea.KeyMsg{Type: tea.KeyEnter}
	}
	return tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune(value)}
}

func TestBuildPromptIncludesWorkflowAndRequirements(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA"})
	if err != nil {
		t.Fatal(err)
	}

	for _, expected := range []string{
		"# gacha auto",
		"Workflow library:",
		"# gacha entry",
		"User request:\nNVDA",
		"Always use current web search",
		"Easy Basic Report",
		"Source Log",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain %q", expected)
		}
	}
}

func TestBuildPromptAutoClassifiesAndRequiresFreshData(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA", "지금", "살까?"})
	if err != nil {
		t.Fatal(err)
	}

	for _, expected := range []string{
		"# gacha auto",
		"Classify the user's request",
		"Always use current web search",
		"even if the user does not ask",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain %q", expected)
		}
	}
}

func TestBuildPromptUsesKoreanForKoreanQuestion(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA", "지금", "사도", "될까?"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(prompt, "Write the final report in Korean") {
		t.Fatalf("prompt did not request Korean response")
	}
}

func TestBuildPromptLocksReportStructure(t *testing.T) {
	prompt, err := buildPrompt([]string{"What should I buy?"})
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"Report structure contract:",
		"The final answer must start with the Easy Basic Report",
		"Write for ordinary users, not investment professionals.",
		"The Basic Report is decision-ready",
		"The Detailed Analysis is the verification layer",
		"Include Detailed Analysis only when",
		"Use simple tables only when they make the answer easier to compare",
		"## Easy Basic Report",
		"### 3. Decision Rules",
		"### 5. Data Check",
		"### 6. More Detail Options",
		"the user knows what they can ask for next",
		"## Detailed Analysis",
		"### G. Source Log",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain report contract detail %q", expected)
		}
	}
}

func TestBuildDetailedPromptContinuesFromBasicReport(t *testing.T) {
	prompt, err := buildDetailedPrompt("NVDA 지금 사도 될까?", "## Easy Basic Report\n\nWatch")
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"# gacha detailed analysis",
		"User request:\nNVDA 지금 사도 될까?",
		"Existing basic report:",
		"Write the detailed analysis in Korean",
		`Produce only the "Detailed Analysis" section`,
		"Use these headings in order",
		"Use current web search or current market-data tools again",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("detailed prompt did not contain %q", expected)
		}
	}
}

func TestSaveReportWritesMarkdownUnderDataHome(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)

	path, err := saveReport("NVDA 지금 사도 될까?", "# Report\n\nBody")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(path, dir+"/gacha/reports/") {
		t.Fatalf("unexpected report path: %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	for _, expected := range []string{
		"# Report",
		"Generated by: gacha",
		"Original question: NVDA 지금 사도 될까?",
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("saved report did not contain %q", expected)
		}
	}
}

func TestReportFileNameUsesReadableSlug(t *testing.T) {
	got := reportFileName(time.Date(2026, 5, 30, 12, 34, 56, 0, time.UTC), "NVDA 지금 사도 될까?")
	if got != "20260530-123456-nvda-지금-사도-될까.md" {
		t.Fatalf("unexpected file name: %s", got)
	}
}

func TestReportSaveAnswerParsing(t *testing.T) {
	for _, answer := range []string{"y", "yes", "Y", "예", "네"} {
		if !wantsSaveReport(answer) {
			t.Fatalf("expected %q to save", answer)
		}
	}
	for _, answer := range []string{"n", "no", "N", "아니요", "아니오"} {
		if !refusesSaveReport(answer) {
			t.Fatalf("expected %q to refuse save", answer)
		}
	}
	if wantsSaveReport("maybe") || refusesSaveReport("maybe") {
		t.Fatal("unexpected parse for ambiguous answer")
	}
}

func TestDetailedAnalysisAnswerParsing(t *testing.T) {
	for _, answer := range []string{"d", "detail", "details", "상세", "상세분석", "자세히", "더 자세히"} {
		if !wantsDetailedAnalysis(answer) {
			t.Fatalf("expected %q to request details", answer)
		}
	}
	if wantsDetailedAnalysis("new question") {
		t.Fatal("unexpected detail parse for ordinary text")
	}
}

func TestDetectLanguageFromLocale(t *testing.T) {
	lang := detectLanguageFromEnv(func(key string) string {
		if key == "LANG" {
			return "ko_KR.UTF-8"
		}
		return ""
	})
	if lang != languageKorean {
		t.Fatalf("unexpected language: %s", lang)
	}
}

func TestResponseLanguageFallsBackToDetectedLocale(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	t.Setenv("LANG", "en_US.UTF-8")
	if got := responseLanguage("Should I buy NVDA now?"); got != languageEnglish {
		t.Fatalf("unexpected language: %s", got)
	}
	if got := responseLanguage("NVDA 지금 사도 될까?"); got != languageKorean {
		t.Fatalf("unexpected language: %s", got)
	}
}

func TestDetectLanguageUsesConfigOverride(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	t.Setenv("GACHA_LANG", "")
	t.Setenv("LANG", "en_US.UTF-8")
	if err := saveGachaConfig(gachaConfig{Language: languageSettingKorean}); err != nil {
		t.Fatal(err)
	}
	if got := detectLanguage(); got != languageKorean {
		t.Fatalf("unexpected language: %s", got)
	}
}

func TestGachaLangEnvOverridesConfigLanguage(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	t.Setenv("GACHA_LANG", "en")
	if err := saveGachaConfig(gachaConfig{Language: languageSettingKorean}); err != nil {
		t.Fatal(err)
	}
	if got := detectLanguage(); got != languageEnglish {
		t.Fatalf("unexpected language: %s", got)
	}
}

func TestShellQuote(t *testing.T) {
	got := shellQuote("can't")
	if got != "'can'\\''t'" {
		t.Fatalf("unexpected quote: %s", got)
	}
}

func TestOpenCodeRunArgsUsesExplicitModel(t *testing.T) {
	got := openCodeRunArgs("hello", "openai/gpt-5.1-codex")
	want := []string{"run", "--model", "openai/gpt-5.1-codex", "hello"}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("unexpected args: %#v", got)
	}
}

func TestPreferredOpenCodeModelAllowsEnvOverride(t *testing.T) {
	t.Setenv("GACHA_OPENCODE_MODEL", "anthropic/claude-sonnet-4-5")
	if got := resolveOpenCodeModel(); got.Model != "anthropic/claude-sonnet-4-5" {
		t.Fatalf("unexpected model: %#v", got)
	}
}

func TestOpenAIChatGPTAuthDetection(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)
	authDir := dir + "/opencode"
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(authDir+"/auth.json", []byte(`{"openai":{"type":"oauth"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	if !hasOpenAIChatGPTAuth() {
		t.Fatal("expected OpenAI OAuth auth to be detected")
	}
}

func TestResolveOpenCodeModelUsesConfigDefault(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	t.Setenv("XDG_DATA_HOME", dir)
	t.Setenv("GACHA_OPENCODE_MODEL", "")
	configDir := dir + "/gacha"
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configDir+"/config.json", []byte(`{"model":"opencode-default"}`), 0o600); err != nil {
		t.Fatal(err)
	}
	got := resolveOpenCodeModel()
	if got.Model != "" || !strings.Contains(got.Reason, "OpenCode default") {
		t.Fatalf("unexpected model resolution: %#v", got)
	}
}

func TestSaveGachaConfigWritesModelAndLanguage(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	want := gachaConfig{Model: "opencode-default", Language: "ko", Theme: "dark"}
	if err := saveGachaConfig(want); err != nil {
		t.Fatal(err)
	}
	got, err := loadGachaConfig()
	if err != nil {
		t.Fatal(err)
	}
	if got.Model != want.Model || got.Language != want.Language || got.Theme != want.Theme {
		t.Fatalf("unexpected config: %#v", got)
	}
}

func TestRunConfigCommandSetsModelAndLanguage(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	if err := runConfigCommand([]string{"set", "model", "OpenCode-Default"}); err != nil {
		t.Fatal(err)
	}
	if err := runConfigCommand([]string{"set", "language", "ko"}); err != nil {
		t.Fatal(err)
	}
	if err := runConfigCommand([]string{"set", "theme", "light"}); err != nil {
		t.Fatal(err)
	}
	got, err := loadGachaConfig()
	if err != nil {
		t.Fatal(err)
	}
	if got.Model != "opencode-default" || got.Language != "ko" || got.Theme != "light" {
		t.Fatalf("unexpected config: %#v", got)
	}
}

func TestRunConfigCommandRejectsInvalidValues(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	if err := runConfigCommand([]string{"set", "model", "bad-model"}); err == nil {
		t.Fatal("expected invalid model error")
	}
	if err := runConfigCommand([]string{"set", "language", "fr"}); err == nil {
		t.Fatal("expected invalid language error")
	}
	if err := runConfigCommand([]string{"set", "theme", "neon"}); err == nil {
		t.Fatal("expected invalid theme error")
	}
}

func TestConfigWithDefaults(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	config, err := configWithDefaults()
	if err != nil {
		t.Fatal(err)
	}
	if config.Model != modelSettingAuto || config.Language != languageSettingAuto || config.Theme != themeSettingSystem {
		t.Fatalf("unexpected default config: %#v", config)
	}
}

func TestThemeContentShowsInteractivePreviews(t *testing.T) {
	for _, tc := range []struct {
		name     string
		text     uiText
		expected []string
	}{
		{
			name: "english",
			text: englishText(),
			expected: []string{
				"Themes",
				"Active: System",
				"Use ↑/↓ and enter",
				"System",
				"Dark",
				"Light",
				"Gacha",
				"Preview",
				"select this theme",
			},
		},
		{
			name: "korean",
			text: koreanText(),
			expected: []string{
				"테마",
				"현재: 시스템",
				"↑/↓로 이동하고 enter로 선택",
				"시스템",
				"다크",
				"라이트",
				"Gacha",
				"예시",
				"이 테마 선택",
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Setenv("XDG_CONFIG_HOME", t.TempDir())
			got := stripANSI(themeContent(tc.text))
			for _, expected := range tc.expected {
				if !strings.Contains(got, expected) {
					t.Fatalf("theme content missing %q:\n%s", expected, got)
				}
			}
			for _, line := range strings.Split(got, "\n") {
				if lipgloss.Width(line) > 80 {
					t.Fatalf("line width %d exceeds 80: %q\n%s", lipgloss.Width(line), line, got)
				}
			}
		})
	}
}

func TestThemeContentReflectsSavedTheme(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	if err := updateConfigTheme(themeSettingLight); err != nil {
		t.Fatal(err)
	}
	got := stripANSI(themeContent(englishText()))
	if !strings.Contains(got, "Active: Light") {
		t.Fatalf("theme content did not reflect saved theme:\n%s", got)
	}
}

func TestTUIThemeCommandSavesAndAppliesTheme(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	model := newTUIModel("0.1.27")
	next, cmd := model.handleThemeSetting("/theme light")
	if cmd != nil {
		t.Fatal("unexpected command")
	}
	updated := next.(tuiModel)
	got, err := loadGachaConfig()
	if err != nil {
		t.Fatal(err)
	}
	if got.Theme != themeSettingLight {
		t.Fatalf("unexpected theme config: %#v", got)
	}
	if !strings.Contains(stripANSI(updated.view.View()), "Active: Light") {
		t.Fatalf("theme view did not show previews:\n%s", stripANSI(updated.view.View()))
	}
}

func TestTUIThemeCommandOpensSelectableThemeChoice(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	model := newTUIModel("0.1.27")

	next, cmd := model.handleSubmit("/theme")
	if cmd != nil {
		t.Fatal("unexpected command")
	}
	updated := next.(tuiModel)
	if updated.choice == nil || updated.choice.Kind != choiceTheme {
		t.Fatalf("expected theme choice, got %#v", updated.choice)
	}

	next, cmd = updated.Update(keyMsg("down"))
	if cmd != nil {
		t.Fatal("unexpected command")
	}
	updated = next.(tuiModel)
	if updated.choice.Selected != 1 {
		t.Fatalf("expected second theme selected, got %d", updated.choice.Selected)
	}

	next, cmd = updated.Update(keyMsg("enter"))
	if cmd != nil {
		t.Fatal("unexpected command")
	}
	updated = next.(tuiModel)
	config, err := loadGachaConfig()
	if err != nil {
		t.Fatal(err)
	}
	if config.Theme != themeSettingDark {
		t.Fatalf("unexpected theme config: %#v", config)
	}
	if updated.choice == nil || updated.choice.Selected != 1 {
		t.Fatalf("expected theme choice to stay active after selection: %#v", updated.choice)
	}
}

func TestTUILanguageAndModelCommandsOpenChoices(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	for _, tc := range []struct {
		value string
		kind  choiceKind
		title string
	}{
		{value: "/language", kind: choiceLanguage, title: "Language"},
		{value: "/model", kind: choiceModel, title: "Model"},
	} {
		t.Run(tc.value, func(t *testing.T) {
			model := newTUIModel("0.1.27")
			next, cmd := model.handleSubmit(tc.value)
			if cmd != nil {
				t.Fatal("unexpected command")
			}
			updated := next.(tuiModel)
			if updated.choice == nil || updated.choice.Kind != tc.kind {
				t.Fatalf("expected %s choice, got %#v", tc.kind, updated.choice)
			}
			if !strings.Contains(stripANSI(updated.view.View()), tc.title) {
				t.Fatalf("choice view missing title %q:\n%s", tc.title, stripANSI(updated.view.View()))
			}
		})
	}
}

func TestTUIUnknownSlashCommandDoesNotRunPrompt(t *testing.T) {
	model := newTUIModel("0.1.27")
	next, cmd := model.handleSubmit("/setting")
	if cmd != nil {
		t.Fatal("unknown slash command should not run a prompt command")
	}
	updated := next.(tuiModel)
	got := stripANSI(updated.view.View())
	for _, expected := range []string{"Unknown command: /setting", "Command palette"} {
		if !strings.Contains(got, expected) {
			t.Fatalf("unknown command view missing %q:\n%s", expected, got)
		}
	}
}

func TestOnboardingContentReflectsSetupState(t *testing.T) {
	text := englishText()
	if got := onboardingContent(text, 80, setupReady); got != "" {
		t.Fatalf("expected no onboarding for ready state, got %q", got)
	}
	if got := onboardingContent(text, 80, setupRuntimeMissing); !strings.Contains(stripANSI(got), "OpenCode is not installed yet") {
		t.Fatalf("unexpected runtime onboarding: %q", got)
	}
	if got := onboardingContent(text, 80, setupProviderMissing); !strings.Contains(stripANSI(got), "no AI provider") {
		t.Fatalf("unexpected provider onboarding: %q", got)
	}
}

func TestWelcomeContentIsDecisionDesk(t *testing.T) {
	got := stripANSI(welcomeContent("0.1.27", englishText(), 80, 16))
	for _, expected := range []string{
		"What are you deciding?",
		"Decision desk",
		"Buy",
		"Find",
		"Hold",
		"Exit",
		"Portfolio",
		"You'll get",
	} {
		if !strings.Contains(got, expected) {
			t.Fatalf("welcome content missing %q:\n%s", expected, got)
		}
	}
	for _, unwanted := range []string{
		"Ask -> Fresh data",
		"[Fresh data required]",
		"[No trading]",
	} {
		if strings.Contains(got, unwanted) {
			t.Fatalf("welcome content kept decorative element %q:\n%s", unwanted, got)
		}
	}
}

func TestWelcomeContentFitsCommonTerminalSizes(t *testing.T) {
	for _, tc := range []struct {
		name   string
		width  int
		height int
		text   uiText
	}{
		{name: "quarter english", width: 80, height: 16, text: englishText()},
		{name: "half english", width: 170, height: 24, text: englishText()},
		{name: "quarter korean", width: 80, height: 16, text: koreanText()},
		{name: "half korean", width: 170, height: 24, text: koreanText()},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := stripANSI(welcomeContent("0.1.27", tc.text, tc.width, tc.height))
			for _, line := range strings.Split(got, "\n") {
				if lipgloss.Width(line) > tc.width {
					t.Fatalf("line width %d exceeds %d: %q\n%s", lipgloss.Width(line), tc.width, line, got)
				}
			}
		})
	}
}

func TestTUIViewFitsCommonTerminalSizes(t *testing.T) {
	for _, tc := range []struct {
		name   string
		width  int
		height int
	}{
		{name: "quarter", width: 80, height: 24},
		{name: "half", width: 120, height: 30},
		{name: "full", width: 180, height: 36},
	} {
		t.Run(tc.name, func(t *testing.T) {
			model := newTUIModel("0.1.27")
			model.width = tc.width
			model.height = tc.height
			model.view.Width = max(30, tc.width-8)
			model.view.Height = max(6, tc.height-8)
			got := stripANSI(model.View())
			for _, line := range strings.Split(got, "\n") {
				if lipgloss.Width(line) > tc.width {
					t.Fatalf("line width %d exceeds %d: %q\n%s", lipgloss.Width(line), tc.width, line, got)
				}
			}
			if strings.Contains(got, "Checks fresh data") {
				t.Fatalf("status bar repeated safety copy:\n%s", got)
			}
			if tc.name == "full" {
				for _, expected := range []string{"Context", "Decision types", "Decision desk", "Ready"} {
					if !strings.Contains(got, expected) {
						t.Fatalf("full layout missing %q:\n%s", expected, got)
					}
				}
				if strings.Contains(got, "No saved reports yet") {
					t.Fatalf("home context showed empty recent state:\n%s", got)
				}
				railWidth, _ := splitLayoutWidths(max(40, tc.width-4))
				foundPrompt := false
				for _, line := range strings.Split(got, "\n") {
					promptColumn := strings.Index(line, "Ask:")
					if promptColumn < 0 {
						continue
					}
					foundPrompt = true
					if promptColumn < railWidth {
						t.Fatalf("full layout prompt crossed into the context rail at column %d before rail width %d:\n%s", promptColumn, railWidth, got)
					}
				}
				if !foundPrompt {
					t.Fatalf("full layout missing prompt input:\n%s", got)
				}
			}
		})
	}
}

func TestTUICommandViewsFitQuarterTerminal(t *testing.T) {
	for _, command := range []string{"/theme", "/help"} {
		t.Run(command, func(t *testing.T) {
			t.Setenv("XDG_CONFIG_HOME", t.TempDir())
			model := newTUIModel("0.1.27")
			next, cmd := model.handleSubmit(command)
			if cmd != nil {
				t.Fatal("unexpected command")
			}
			updated := next.(tuiModel)
			updated.width = 80
			updated.height = 24
			got := stripANSI(updated.View())
			for _, line := range strings.Split(got, "\n") {
				if lipgloss.Width(line) > 80 {
					t.Fatalf("line width %d exceeds 80: %q\n%s", lipgloss.Width(line), line, got)
				}
			}
			for _, fragment := range []string{
				"│  pro                                                                     │",
				"│  /languag                                                                │",
			} {
				if strings.Contains(got, fragment) {
					t.Fatalf("command view contains wrapped fragment %q:\n%s", fragment, got)
				}
			}
		})
	}
}

func TestTUIFullLayoutKeepsLocalizedPromptInRightPanel(t *testing.T) {
	for _, tc := range []struct {
		name       string
		text       uiText
		promptText string
	}{
		{name: "english", text: englishText(), promptText: "Ask:"},
		{name: "korean", text: koreanText(), promptText: "예:"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			model := newTUIModel("0.1.27")
			model.text = tc.text
			model.input.Placeholder = tc.text.InputPlaceholder
			model.width = 180
			model.height = 36
			got := stripANSI(model.View())
			railWidth, _ := splitLayoutWidths(max(40, model.width-4))
			foundPrompt := false
			for _, line := range strings.Split(got, "\n") {
				promptColumn := strings.Index(line, tc.promptText)
				if promptColumn < 0 {
					continue
				}
				foundPrompt = true
				if promptColumn < railWidth {
					t.Fatalf("localized prompt crossed into the context rail at column %d before rail width %d:\n%s", promptColumn, railWidth, got)
				}
			}
			if !foundPrompt {
				t.Fatalf("missing localized prompt %q:\n%s", tc.promptText, got)
			}
		})
	}
}

func TestTUIStatusBarRendersBelowWorkspace(t *testing.T) {
	model := newTUIModel("0.1.27")
	model.width = 180
	model.height = 36
	got := stripANSI(model.View())
	promptLine := -1
	statusLine := -1
	panelBottomLine := -1
	for i, line := range strings.Split(got, "\n") {
		if strings.Contains(line, "Ask:") {
			promptLine = i
		}
		if strings.Contains(line, "Ready") && strings.Contains(line, "Mode") {
			statusLine = i
		}
		if strings.Contains(line, "╰") && statusLine < 0 {
			panelBottomLine = i
		}
	}
	if promptLine < 0 {
		t.Fatalf("missing prompt input:\n%s", got)
	}
	if statusLine <= promptLine {
		t.Fatalf("status bar did not render below workspace; prompt line %d status line %d:\n%s", promptLine, statusLine, got)
	}
	if panelBottomLine < 0 {
		t.Fatalf("missing split panel bottom border:\n%s", got)
	}
	if panelBottomLine-promptLine > 5 {
		t.Fatalf("prompt input is too far above right panel bottom; prompt line %d panel bottom line %d:\n%s", promptLine, panelBottomLine, got)
	}
}

func TestContextRailReflectsTUIState(t *testing.T) {
	model := newTUIModel("0.1.27")
	model.width = 180
	model.height = 36
	model.view.Width = 172
	model.view.Height = 28

	home := stripANSI(model.View())
	for _, expected := range []string{"Context", "Decision types"} {
		if !strings.Contains(home, expected) {
			t.Fatalf("home context missing %q:\n%s", expected, home)
		}
	}
	if strings.Contains(home, "No saved reports yet") {
		t.Fatalf("home context showed empty recent state:\n%s", home)
	}

	model.busy = true
	model.query = "Should I buy NVDA now?"
	model.phase = 1
	model.status = model.text.ResearchPhases[1]
	model.view.SetContent(researchingContent(model.query, model.text))
	research := stripANSI(model.View())
	for _, expected := range []string{"Current request", "Should I buy NVDA now?", "Research", "Sources"} {
		if !strings.Contains(research, expected) {
			t.Fatalf("research context missing %q:\n%s", expected, research)
		}
	}

	model.busy = false
	model.mode = model.text.Report
	model.status = model.text.Complete
	model.report = "## Easy Basic Report\n\n### 1. Bottom Line\nWait.\n\n### 3. Decision Rules\nBuy if...\n\n### 4. Biggest Risks\nValuation.\n\n### 5. Data Check\nCurrent price checked."
	model.view.SetContent(model.report)
	report := stripANSI(model.View())
	for _, expected := range []string{"Current request", "Report", "Bottom line", "Decision rules", "Risks", "Data check"} {
		if !strings.Contains(report, expected) {
			t.Fatalf("report context missing %q:\n%s", expected, report)
		}
	}
}

func TestReportActionsExposeNextChoices(t *testing.T) {
	got := stripANSI(renderReportActions(englishText()))
	normalized := strings.Join(strings.Fields(got), " ")
	for _, expected := range []string{"Next", "Use ↑/↓ and enter", "d Detailed analysis", "y Save", "n Skip", "ask a new question"} {
		if !strings.Contains(normalized, expected) {
			t.Fatalf("report actions missing %q:\n%s", expected, got)
		}
	}
}

func TestTUIHelpExposesOnlyUserFacingCommands(t *testing.T) {
	got := stripANSI(helpContent(englishText()))
	for _, expected := range []string{"/home", "/help", "/settings", "/model", "/language", "/theme", "/quit"} {
		if !strings.Contains(got, expected) {
			t.Fatalf("help content missing %q:\n%s", expected, got)
		}
	}
	for _, hidden := range []string{"/doctor", "/setup", "/update"} {
		if strings.Contains(got, hidden) {
			t.Fatalf("help content exposed operational command %q:\n%s", hidden, got)
		}
	}
}

func TestFooterKeepsPrimaryCommandsVisible(t *testing.T) {
	got := stripANSI(renderFooter(120, englishText()))
	for _, expected := range []string{"/help", "/settings", "/theme", "/quit"} {
		if !strings.Contains(got, expected) {
			t.Fatalf("footer missing %q:\n%s", expected, got)
		}
	}
	for _, hidden := range []string{"/doctor", "/setup", "/update"} {
		if strings.Contains(got, hidden) {
			t.Fatalf("footer exposed operational command %q:\n%s", hidden, got)
		}
	}
}

func TestParseOpenCodeModels(t *testing.T) {
	output := "\x1b[0m\nopenai/gpt-5.5\nopenai/gpt-5.5-pro\nnot a model\nopenai/gpt-5.5\n"
	got := parseOpenCodeModels(output)
	want := []string{"openai/gpt-5.5", "openai/gpt-5.5-pro"}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("unexpected models: %#v", got)
	}
}

func TestChooseModelPrefersQualityAndLatest(t *testing.T) {
	got := firstModel(rankModels([]string{
		"openai/gpt-5.5-mini",
		"openai/gpt-5.1-codex",
		"openai/gpt-5.5-pro",
		"openai/gpt-5.5",
		"openai/gpt-5",
	}, "openai"))
	if got != "openai/gpt-5.5" {
		t.Fatalf("unexpected model: %s", got)
	}
}

func TestRankModelsPrefersNewestOpenAIBaseFrontier(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)
	authDir := dir + "/opencode"
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(authDir+"/auth.json", []byte(`{"openai":{"type":"oauth"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	got := rankModels([]string{
		"openai/gpt-5.6-pro",
		"openai/gpt-5.6-fast",
		"openai/gpt-5.6",
		"openai/gpt-5.5-pro",
		"openai/gpt-5.5",
		"openai/gpt-5.1-codex",
	}, "openai")
	if got[0] != "openai/gpt-5.6" {
		t.Fatalf("unexpected ranked models: %#v", got)
	}
}

func TestRankModelsKeepsOpenAICodexBehindFrontierBase(t *testing.T) {
	got := rankModels([]string{
		"openai/gpt-5.3-codex-spark",
		"openai/gpt-5.3-codex",
		"openai/gpt-5.5",
		"openai/gpt-5.5-fast",
	}, "openai")
	if got[0] != "openai/gpt-5.5" {
		t.Fatalf("unexpected ranked models: %#v", got)
	}
}

func TestChooseModelPenalizesSmallModels(t *testing.T) {
	got := chooseModel([]string{
		"google/gemini-3-flash",
		"google/gemini-2.5-pro",
	})
	if got != "google/gemini-2.5-pro" {
		t.Fatalf("unexpected model: %s", got)
	}
}

func TestUnsupportedChatGPTModelErrorDetection(t *testing.T) {
	output := `Bad Request: {"detail":"The 'gpt-5.5-pro' model is not supported when using Codex with a ChatGPT account."}`
	if !isUnsupportedChatGPTModelError(output) {
		t.Fatal("expected unsupported ChatGPT model error")
	}
}

func TestReleaseAssetNameUsesWindowsZip(t *testing.T) {
	if got := releaseAssetName("windows", "amd64"); got != "gacha-windows-amd64.zip" {
		t.Fatalf("unexpected Windows asset: %s", got)
	}
	if got := releaseAssetName("linux", "amd64"); got != "gacha-linux-amd64.tar.gz" {
		t.Fatalf("unexpected Linux asset: %s", got)
	}
}

func TestReleaseAssetURLForUsesTargetArchive(t *testing.T) {
	got := releaseAssetURLFor("v0.1.27", "windows", "arm64")
	want := "https://github.com/dkstm95/gacha/releases/download/v0.1.27/gacha-windows-arm64.zip"
	if got != want {
		t.Fatalf("unexpected URL:\n got: %s\nwant: %s", got, want)
	}
}

func TestSelfUpdateUnsupportedOnWindows(t *testing.T) {
	if selfUpdateSupported("windows") {
		t.Fatal("expected Windows self-update to be disabled")
	}
	if !selfUpdateSupported("linux") || !selfUpdateSupported("darwin") {
		t.Fatal("expected Unix self-update to stay enabled")
	}
	if !strings.Contains(windowsUpdateUnsupportedMessage(), "gacha-windows-amd64.zip") {
		t.Fatal("Windows update message should point users to Windows ZIP artifacts")
	}
}
