package app

import (
	"os"
	"strings"
	"testing"
	"time"
)

func TestBuildPromptIncludesWorkflowAndRequirements(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA"})
	if err != nil {
		t.Fatal(err)
	}

	for _, expected := range []string{
		"# gacha auto",
		"Workflow library:",
		"# gacha entry",
		"User request:\nNVDA",
		"Always use current web search",
		"Provenance Appendix",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain %q", expected)
		}
	}
}

func TestBuildPromptAutoClassifiesAndRequiresFreshData(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA", "지금", "살까?"})
	if err != nil {
		t.Fatal(err)
	}

	for _, expected := range []string{
		"# gacha auto",
		"Classify the user's request",
		"Always use current web search",
		"even if the user does not ask",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain %q", expected)
		}
	}
}

func TestBuildPromptUsesKoreanForKoreanQuestion(t *testing.T) {
	prompt, err := buildPrompt([]string{"NVDA", "지금", "사도", "될까?"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(prompt, "Write the final report in Korean") {
		t.Fatalf("prompt did not request Korean response")
	}
}

func TestBuildPromptLocksReportStructure(t *testing.T) {
	prompt, err := buildPrompt([]string{"What should I buy?"})
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"Report structure contract:",
		"The final answer must use the 14 numbered sections",
		"Do not drop, merge, or reorder sections.",
		`write "Not applicable"`,
		"Use the required tables for candidate ranking, price zones, scenarios, action conditions, monitoring, and provenance.",
		"## 1. Request Type",
		"## 14. Provenance Appendix",
	} {
		if !strings.Contains(prompt, expected) {
			t.Fatalf("prompt did not contain report contract detail %q", expected)
		}
	}
}

func TestSaveReportWritesMarkdownUnderDataHome(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)

	path, err := saveReport("NVDA 지금 사도 될까?", "# Report\n\nBody")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(path, dir+"/gacha/reports/") {
		t.Fatalf("unexpected report path: %s", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	for _, expected := range []string{
		"# Report",
		"Generated by: gacha",
		"Original question: NVDA 지금 사도 될까?",
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("saved report did not contain %q", expected)
		}
	}
}

func TestReportFileNameUsesReadableSlug(t *testing.T) {
	got := reportFileName(time.Date(2026, 5, 30, 12, 34, 56, 0, time.UTC), "NVDA 지금 사도 될까?")
	if got != "20260530-123456-nvda-지금-사도-될까.md" {
		t.Fatalf("unexpected file name: %s", got)
	}
}

func TestReportSaveAnswerParsing(t *testing.T) {
	for _, answer := range []string{"y", "yes", "Y", "예", "네"} {
		if !wantsSaveReport(answer) {
			t.Fatalf("expected %q to save", answer)
		}
	}
	for _, answer := range []string{"n", "no", "N", "아니요", "아니오"} {
		if !refusesSaveReport(answer) {
			t.Fatalf("expected %q to refuse save", answer)
		}
	}
	if wantsSaveReport("maybe") || refusesSaveReport("maybe") {
		t.Fatal("unexpected parse for ambiguous answer")
	}
}

func TestDetectLanguageFromLocale(t *testing.T) {
	lang := detectLanguageFromEnv(func(key string) string {
		if key == "LANG" {
			return "ko_KR.UTF-8"
		}
		return ""
	})
	if lang != languageKorean {
		t.Fatalf("unexpected language: %s", lang)
	}
}

func TestResponseLanguageFallsBackToDetectedLocale(t *testing.T) {
	t.Setenv("LANG", "en_US.UTF-8")
	if got := responseLanguage("Should I buy NVDA now?"); got != languageEnglish {
		t.Fatalf("unexpected language: %s", got)
	}
	if got := responseLanguage("NVDA 지금 사도 될까?"); got != languageKorean {
		t.Fatalf("unexpected language: %s", got)
	}
}

func TestShellQuote(t *testing.T) {
	got := shellQuote("can't")
	if got != "'can'\\''t'" {
		t.Fatalf("unexpected quote: %s", got)
	}
}

func TestOpenCodeRunArgsUsesExplicitModel(t *testing.T) {
	got := openCodeRunArgs("hello", "openai/gpt-5.1-codex")
	want := []string{"run", "--model", "openai/gpt-5.1-codex", "hello"}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("unexpected args: %#v", got)
	}
}

func TestPreferredOpenCodeModelAllowsEnvOverride(t *testing.T) {
	t.Setenv("GACHA_OPENCODE_MODEL", "anthropic/claude-sonnet-4-5")
	if got := resolveOpenCodeModel(); got.Model != "anthropic/claude-sonnet-4-5" {
		t.Fatalf("unexpected model: %#v", got)
	}
}

func TestOpenAIChatGPTAuthDetection(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)
	authDir := dir + "/opencode"
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(authDir+"/auth.json", []byte(`{"openai":{"type":"oauth"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	if !hasOpenAIChatGPTAuth() {
		t.Fatal("expected OpenAI OAuth auth to be detected")
	}
}

func TestResolveOpenCodeModelUsesConfigDefault(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	t.Setenv("XDG_DATA_HOME", dir)
	t.Setenv("GACHA_OPENCODE_MODEL", "")
	configDir := dir + "/gacha"
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configDir+"/config.json", []byte(`{"model":"opencode-default"}`), 0o600); err != nil {
		t.Fatal(err)
	}
	got := resolveOpenCodeModel()
	if got.Model != "" || !strings.Contains(got.Reason, "OpenCode default") {
		t.Fatalf("unexpected model resolution: %#v", got)
	}
}

func TestParseOpenCodeModels(t *testing.T) {
	output := "\x1b[0m\nopenai/gpt-5.5\nopenai/gpt-5.5-pro\nnot a model\nopenai/gpt-5.5\n"
	got := parseOpenCodeModels(output)
	want := []string{"openai/gpt-5.5", "openai/gpt-5.5-pro"}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("unexpected models: %#v", got)
	}
}

func TestChooseModelPrefersQualityAndLatest(t *testing.T) {
	got := firstModel(rankModels([]string{
		"openai/gpt-5.5-mini",
		"openai/gpt-5.1-codex",
		"openai/gpt-5.5-pro",
		"openai/gpt-5.5",
		"openai/gpt-5",
	}, "openai"))
	if got != "openai/gpt-5.5" {
		t.Fatalf("unexpected model: %s", got)
	}
}

func TestRankModelsPrefersNewestOpenAIBaseFrontier(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_DATA_HOME", dir)
	authDir := dir + "/opencode"
	if err := os.MkdirAll(authDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(authDir+"/auth.json", []byte(`{"openai":{"type":"oauth"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	got := rankModels([]string{
		"openai/gpt-5.6-pro",
		"openai/gpt-5.6-fast",
		"openai/gpt-5.6",
		"openai/gpt-5.5-pro",
		"openai/gpt-5.5",
		"openai/gpt-5.1-codex",
	}, "openai")
	if got[0] != "openai/gpt-5.6" {
		t.Fatalf("unexpected ranked models: %#v", got)
	}
}

func TestRankModelsKeepsOpenAICodexBehindFrontierBase(t *testing.T) {
	got := rankModels([]string{
		"openai/gpt-5.3-codex-spark",
		"openai/gpt-5.3-codex",
		"openai/gpt-5.5",
		"openai/gpt-5.5-fast",
	}, "openai")
	if got[0] != "openai/gpt-5.5" {
		t.Fatalf("unexpected ranked models: %#v", got)
	}
}

func TestChooseModelPenalizesSmallModels(t *testing.T) {
	got := chooseModel([]string{
		"google/gemini-3-flash",
		"google/gemini-2.5-pro",
	})
	if got != "google/gemini-2.5-pro" {
		t.Fatalf("unexpected model: %s", got)
	}
}

func TestUnsupportedChatGPTModelErrorDetection(t *testing.T) {
	output := `Bad Request: {"detail":"The 'gpt-5.5-pro' model is not supported when using Codex with a ChatGPT account."}`
	if !isUnsupportedChatGPTModelError(output) {
		t.Fatal("expected unsupported ChatGPT model error")
	}
}
