package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"
)

func saveReport(query string, report string) (string, error) {
	report = strings.TrimSpace(report)
	if report == "" {
		return "", fmt.Errorf("empty report")
	}
	dir := reportsDir()
	if dir == "" {
		return "", fmt.Errorf("report directory not available")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, reportFileName(time.Now(), query))
	content := reportFileContent(query, report)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

func reportsDir() string {
	base := os.Getenv("XDG_DATA_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		base = filepath.Join(home, ".local", "share")
	}
	return filepath.Join(base, "gacha", "reports")
}

func reportFileName(now time.Time, query string) string {
	stamp := now.Format("20060102-150405")
	slug := slugify(query)
	if slug == "" {
		slug = "report"
	}
	return stamp + "-" + slug + ".md"
}

func reportFileContent(query string, report string) string {
	return strings.TrimSpace(report) + "\n\n---\n\n" +
		"Generated by: gacha\n\n" +
		"Original question: " + strings.TrimSpace(query) + "\n"
}

func slugify(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var builder strings.Builder
	lastDash := false
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash && builder.Len() > 0 {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	slug := strings.Trim(builder.String(), "-")
	runes := []rune(slug)
	if len(runes) > 48 {
		slug = string(runes[:48])
		slug = strings.Trim(slug, "-")
	}
	return slug
}
