package app

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"
)

func saveReport(query string, report string) (string, error) {
	return saveReportAt(query, report, time.Now())
}

func (a *App) saveReport(query string, report string) (string, error) {
	return saveReportAt(query, report, a.env.now())
}

func saveReportAt(query string, report string, now time.Time) (string, error) {
	report = strings.TrimSpace(report)
	if report == "" {
		return "", fmt.Errorf("empty report")
	}
	dir := reportsDir()
	if dir == "" {
		return "", fmt.Errorf("report directory not available")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, reportFileName(now, query))
	content := reportFileContent(query, report)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

type reportAction int

const (
	reportActionNone reportAction = iota
	reportActionSave
	reportActionSkip
	reportActionDetail
	reportActionNewQuestion
)

func askReportAction(text uiText) (reportAction, string, error) {
	if !isInteractiveTerminal() {
		return reportActionNone, "", nil
	}
	fmt.Fprintln(os.Stderr)
	fmt.Fprint(os.Stderr, text.SavePrompt+" ")
	reader := bufio.NewReader(os.Stdin)
	answer, err := reader.ReadString('\n')
	if err != nil {
		return reportActionNone, "", err
	}
	answer = strings.TrimSpace(answer)
	switch {
	case wantsSaveReport(answer):
		return reportActionSave, "", nil
	case refusesSaveReport(answer):
		return reportActionSkip, "", nil
	case wantsDetailedAnalysis(answer):
		return reportActionDetail, "", nil
	case answer != "":
		return reportActionNewQuestion, answer, nil
	default:
		return reportActionNone, "", nil
	}
}

func wantsSaveReport(answer string) bool {
	normalized := strings.ToLower(strings.TrimSpace(answer))
	return normalized == "y" || normalized == "yes" || normalized == "ㅛ" || normalized == "예" || normalized == "네"
}

func refusesSaveReport(answer string) bool {
	normalized := strings.ToLower(strings.TrimSpace(answer))
	return normalized == "n" || normalized == "no" || normalized == "ㅜ" || normalized == "아니오" || normalized == "아니요"
}

func wantsDetailedAnalysis(answer string) bool {
	normalized := strings.ToLower(strings.TrimSpace(answer))
	switch normalized {
	case "d", "detail", "details", "more", "deep", "detailed analysis", "상세", "상세분석", "자세히", "더 자세히", "깊게":
		return true
	default:
		return false
	}
}

func reportsDir() string {
	base := os.Getenv("XDG_DATA_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return ""
		}
		base = filepath.Join(home, ".local", "share")
	}
	return filepath.Join(base, "gacha", "reports")
}

func reportFileName(now time.Time, query string) string {
	stamp := now.Format("20060102-150405")
	slug := slugify(query)
	if slug == "" {
		slug = "report"
	}
	return stamp + "-" + slug + ".md"
}

func reportFileContent(query string, report string) string {
	return strings.TrimSpace(report) + "\n\n---\n\n" +
		"Generated by: gacha\n\n" +
		"Original question: " + strings.TrimSpace(query) + "\n"
}

func slugify(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var builder strings.Builder
	lastDash := false
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash && builder.Len() > 0 {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	slug := strings.Trim(builder.String(), "-")
	runes := []rune(slug)
	if len(runes) > 48 {
		slug = string(runes[:48])
		slug = strings.Trim(slug, "-")
	}
	return slug
}
